routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@homePage')->name('homePage');

Route::get('/about', 'SiteController@aboutPage')->name('aboutPage');

Route::get('/services', 'SiteController@servicePage')->name('servicePage');

Route::get('/contact', 'SiteController@contactPage')->name('contactPage');

Route::get('/portfolio', 'SiteController@portfolioPage')->name('portfolioPage');

Route::get('/portfolio/{slug}', 'SiteController@singleProject')->name('singleProject');

// Admin Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('admin', 'AdminController@index')->name('admin.index');
Route::get('admin/projects', 'ProjectController@index')->name('admin.projects');
Route::get('admin/subscribers', 'SubscriberController@index')->name('admin.subscribers');
Route::get('admin/pages', 'PagesController@index')->name('admin.pages');

// Projects Routes
Route::get('admin/projects/create', 'ProjectController@create')->name('admin.projects.create');
Route::post('admin/projects/store', 'ProjectController@store')->name('admin.projects.store');
Route::get('admin/projects/show/{project}', 'ProjectController@show')->name('admin.projects.show');
Route::get('admin/projects/edit/{project}', 'ProjectController@edit')->name('admin.projects.edit');
Route::put('admin/projects/update/{project}', 'ProjectController@update')->name('admin.projects.update');

// Testimonials Routes
Route::get('admin/testimonials', 'TestimonialController@index')->name('admin.testimonials');
Route::get('admin/testimonials/show/{testimonial}', 'TestimonialController@show')->name('admin.testimonials.show');
Route::get('admin/testimonials/edit/{testimonial}', 'TestimonialController@edit')->name('admin.testimonials.edit');
Route::get('admin/testimonials/create', 'TestimonialController@create')->name('admin.testimonials.create');
Route::post('admin/testimonials/store', 'TestimonialController@store')->name('admin.testimonials.store');
Route::put('admin.testimonials/update/{testimonial}', 'TestimonialController@update')->name('admin.testimonials.update');

// Tags Routes
Route::resource('tags', 'TagController');

// Contact Routes
Route::post('contact/message/send', 'MessageController@store')->name('contact.store');

// Newsletter Routes
Route::post('newsletter/subscribe', 'SubscriberController@store')->name('newsletter.subscribe');

// Admin Pages Routes
Route::get('admin/pages/{page}/edit', 'PagesController@edit')->name('admin.pages.edit');
Route::put('admin/pages/{page}/update', 'PagesController@update')->name('admin.pages.update');
Route::post('admin/pages/store', 'PagesController@store')->name('admin.pages.store');
Route::get('admin/pages/create', 'PagesController@create')->name('admin.pages.create');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    public function pages()
    {
    	return $this->belongsToMany(Page::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();

        return view('admin.tags.index', compact('tags'));
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Tag::create(request()->all());

        session()->flash('success', 'Created!');

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        //
    }
}

resources/views/admin/tags/index.blade.php
@extends ('layouts.admin')

@section ('content')

 <header class="header text-white p-0 overflow-hidden" data-overlay="9">

    <div class="container text-center">

      <div class="row h-100">
        <div class="col-lg-8 mx-auto align-self-center mb-8 pt-10">

          <h1>Tags</h1>

        </div>

      </div>

    </div>
 </header>

 <main class="main-content">

 	<div class="container mt-6">

 		<div class="row">

 			<div class="col-md-4">
 				<form action="{{ route('tags.store') }}" method="POST">
 					<div class="form-group">

 						<input type="text" placeholder="Create New Tag" class="form-control" name="name" value="{{ old('name') }}">

 						@csrf
 					</div>

 					<input type="submit" value="Create" class="btn">
 				</form>
 			</div>
 			
		 	<div class="col-md-8">
		 		<table class="table table-striped">
			        <thead>
			          <tr>
			            <th>S/N</th>
			            <th>Name</th>
			            <th>Options</th>
			          </tr>
			        </thead>
			        <tbody>
			        	@foreach ($tags as $t)
			        	<span style="visibility: hidden;">{{ $index++ }}</span>

			          <tr>
			            <th scope="row">{{ $index }}</th>
			            <td>{{ $t->name }}</td>
			            <td> 
							<a href="{{ route('tags.destroy', $t) }}"><i class="fa fa-trash"></i></a> &nbsp; &nbsp;
							<a href="{{ route('tags.edit', $t) }}"><i class="fa fa-pencil"></i></a>
			            </td>
			          </tr>

			          @endforeach
			        </tbody>
			      </table>
		 	</div>

 		</div>

 	</div>

 </main>

@stop